image: alpine/edge
packages:
  - go
  - rsync
sources:
  - https://github.com/sauerbraten/saebs
environment:
  DEPLOY: chef.p1x.pw
secrets:
  - 41a695fb-4229-450d-9aa4-5499f6bcea81
tasks:
  - prepare_go_modules: |
      go env -w GOFLAGS=-mod=vendor
  - build: |
      cd saebs
      go build
  - deploy: |
      cd saebs
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq css templates saebs ci@$DEPLOY:~/saebs/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'killall saebs || true'
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'cd saebs; nohup ./sabes >> log.txt 2>&1 &'
