image: fedora/32
packages:
  - go
  - rsync
sources:
  - https://github.com/sauerbraten/saebs
environment:
  DEPLOY: p1x.pw
secrets:
  - 956ddc04-c911-4147-bc90-30bb08276c3e # ci@p1x.pw ssh key
tasks:
  - prepare_go_modules: |
      go env -w GOFLAGS=-mod=vendor
  - build: |
      cd saebs
      go build
  - deploy: |
      cd saebs
      rsync --rsh="ssh -o StrictHostKeyChecking=no" -rPq css templates saebs ci@$DEPLOY:~/saebs/
      ssh -o StrictHostKeyChecking=no ci@$DEPLOY 'sudo systemctl restart saebs'
